### ISSUE TITLE
Can't login with an error

### ISSUE THREAD

**Issue by neroti9n** [frysztak/orpington-news#94]
hello, i get an error when i was logining
![image](https://user-images.githubusercontent.com/15121488/204298160-84ced464-167f-4e63-baca-284a9949498b.png)
![image](https://user-images.githubusercontent.com/15121488/204298008-b447573e-e574-49f8-b8dd-dd81b77ca4bc.png)

**Comment by neroti9n** [comment]
Not yet...maybe this is the crux of the problem...so i can't use it through NOT HTTPS?

**Comment by frysztak** [comment]
in general you should be able not to use HTTPS, but I missed the fact that [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) is not available in non-secure contexts. I'll prepare patch release with a fix right now

**Comment by frysztak** [comment]
@neroti9n this should be fixed in [v0.9.1](https://github.com/frysztak/orpington-news/releases/tag/0.9.1). please pull newest image and try logging in again

**Comment by neroti9n** [comment]
thanks~

**Comment by neroti9n** [comment]
i have updated to the newest image, it didn' t show last error, but api returned http errorcode 401 Unauthorized

**Comment by frysztak** [comment]
I'll later setup env without HTTPS to debug this

**Comment by frysztak** [comment]
@neroti9n can you try adding environmental variable `DISABLE_SECURE_COOKIE=true`? following sample [`docker-compose.template.yml`](https://github.com/frysztak/orpington-news/blob/master/docker-compose.template.yml):
```yaml
version: '3'
services:
  orpington-news:
    image: ghcr.io/frysztak/orpington-news-api:latest
    container_name: orpington-news
    environment:
      - APP_URL=https://news.my.domain # please change to your actual domain
      - DB_HOST=orpington-news-postgres
      - DB_PASS=dbpass # same pass like `POSTGRES_PASSWORD` below
      - COOKIE_SECRET=<generate unique cookie secret, for details see README>
      - DISABLE_SECURE_COOKIE=true
      # ^^ that's the line
    networks:
      - orpington-news
    restart: always

  orpington-news-postgres:
    image: postgres:14-alpine
    container_name: orpington-news-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - <local directory>:/var/lib/postgresql/data
    networks:
      - orpington-news
    restart: always

networks:
  orpington-news:
```
